### ISSUE TITLE
link to external dict resource if user clicks word not in our list

### ISSUE THREAD

**Issue by CallumBeaney** [goodpals/middle-english-mouse-dictionary#8]
say user clicks a ME word that isn't in our dictionaries
We open a link to an external resource, in a new tab silently in the background. 
Not obtrusive, subtly tells users it's not in our dict, but also gives them an alt they can check if they want.

Refactor previous contextMenu. Bad UX.

**Comment by CallumBeaney** [comment]
Done a very very basic clickable link. Will use events/messages to make it open in background

**Comment by alexobviously** [comment]
As a user I would strongly dislike this behaviour tbh, I don't think anything should ever open a link without explicit action from the user, but the functionality itself sounds pretty useful. We just need to find a better way to trigger it that automatically opening pages in the background.

**Comment by alexobviously** [comment]
How about the context menu option you already added 'query med website' does this?

**Comment by CallumBeaney** [comment]
> How about the context menu option you already added 'query med website' does this?

This is the best option and has now been implemented
